# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp", auto_correct: true

  config.vm.hostname = "bareos-server"

  config.vm.provision "shell",
    path: "script_install_packages.sh"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "bareos-server"]
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    echo "finished"
    echo "ssh vagrant@127.0.0.1 -p 2222"
  EOC


  config.vm.define "bareos-server"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible_bareos.yml"
      ansible.inventory_path = "../remote_hosts"
      #ansible.verbose = "vvvv"
  end

end
